export default [
    {value:'1',text:'Ngân hàng thương mại cổ phần An Bình (ABBANK)'},
    {value:'2',text:'Ngân hàng ACB'},
    {value:'3',text:'Ngân hàng Nông nghiệp (Agribank)'},
    {value:'4',text:'Ngân Hàng TMCP Bắc Á'},
    {value:'5',text:'Ngân hàng đầu tư và phát triển Việt Nam (BIDV)'},
    {value:'6',text:'Ngân hàng Đông Á (DongABank)'},
    {value:'7',text:'Ngân hàng EximBank'},
    {value:'8',text:'Ngan hàng HDBank'},
    {value:'9',text:'Ngân hàng TNHH Indovina (IVB)'},
    {value:'10',text:'Ngân hàng thương mại cổ phần Quân đội'},
    {value:'11',text:'Ngân hàng Hàng Hải (MSBANK)'},
    {value:'12',text:'Ngân hàng Nam Á (NamABank)'},
    {value:'13',text:'Ngân hàng Quốc dân (NCB)'},
    {value:'14',text:'Ngân hàng Phương Đông (OCB)'},
    {value:'15',text:'Ngân hàng Đại Dương (OceanBank)'},
    {value:'16',text:'Ngân hàng TMCP Đại Chúng Việt Nam'},
    {value:'17',text:'Ngân hàng TMCP Sài Gòn Thương Tín (SacomBank)'},
    {value:'18',text:'Ngân hàng thương mại cổ phần Sài Gòn Công Thương'},
    {value:'19',text:'Ngân hàng TMCP Sài Gòn (SCB)'},
    {value:'20',text:'Ngân hàng Thương mại cổ phần Sài Gòn - Hà Nội(SHB)'},
    {value:'21',text:'Ngân hàng Kỹ thương Việt Nam (TechcomBank)'},
    {value:'22',text:'Ngân hàng Tiên Phong (TPBank)'},
    {value:'23',text:'Ngân hàng Việt Nam Thịnh vượng (VPBank)'},
    {value:'24',text:'Ngân Hàng TMCP Đông Nam Á'},
    {value:'25',text:'Ngân hàng Thương mại cổ phần Quốc tế Việt Nam (VIB)'},
    {value:'26',text:'Ngân hàng TMCP Việt Á'},
    {value:'27',text:'Ngân hàng thương mại cổ phần Việt Nam Thương Tín'},
    {value:'28',text:'Ngân Hàng Bản Việt'},
    {value:'29',text:'Ngân hàng Ngoại thương (Vietcombank)'},
    {value:'30',text:'Ngân hàng Công thương (Vietinbank)'},
    {value:'31',text:'Ngân Hàng BIDC'},
    {value:'32',text:'NGÂN HÀNG LIÊN DOANH LÀO - VIỆT'},
    {value:'33',text:'Ngân hàng TNHH MTV Woori Việt Nam'},
    {value:'34',text:'American Express'},
    {value:'35',text:'Thẻ quốc tế Visa'},
    {value:'36',text:'Thẻ quốc tế MasterCard'},
    {value:'37',text:'Thẻ quốc tế JCB'},
    {value:'38',text:'UnionPay International'},
    {value:'39',text:'Ví điện tử VnMart'},
    {value:'40',text:'Cổng thanh toán VNPAYQR'},
    {value:'41',text:'Ví điện tử 1Pay'},
    {value:'42',text:'Ví điện tử FOXPAY'},
    {value:'43',text:'Ví điện tử Vimass'},
    {value:'44',text:'Ví điện tử VINID'},
    {value:'45',text:'Ví điện tử Ví Việt'},
    {value:'46',text:'Ví điện tử VNPTPAY'},
    {value:'47',text:'Ví điện tử YOLO'},
    {value:'47',text:'Ngân Hàng Bản Việt'},
]
